const DATA = [
    {
      id: '1',
      farmName: 'Labyrinth of Crops Farmstead',
      greenhouse: 'Vivid Vines Gardens',
      tomatoesDetected: 1875,
      stemsDetected: 491,
      creationDate: '01/08/2025',
    },
    {
      id: '2',
      farmName: 'Golden Fields Ranch',
      greenhouse: 'Sunlit Acres',
      tomatoesDetected: 6124,
      stemsDetected: 896,
      creationDate: '02/08/2025',
    },
    {
      id: '3',
      farmName: 'Rustic Roots Farm Sunlight',
      greenhouse: 'Meadow Bliss',
      tomatoesDetected: 582,
      stemsDetected: 179,
      creationDate: '02/08/2025',
    },
    {
      id: '4',
      farmName: 'Rustic Roots Farm Sunlight',
      greenhouse: 'Meadow Bliss',
      tomatoesDetected: 582,
      stemsDetected: 179,
      creationDate: '02/08/2025',
    },
    {
      id: '5',
      farmName: 'Rustic Roots Farm Sunlight',
      greenhouse: 'Meadow Bliss',
      tomatoesDetected: 582,
      stemsDetected: 179,
      creationDate: '02/08/2025',
    },
    {
      id: '6',
      farmName: 'Rustic Roots Farm Sunlight',
      greenhouse: 'Meadow Bliss',
      tomatoesDetected: 582,
      stemsDetected: 179,
      creationDate: '02/08/2025',
    },
    {
      id: '7',
      farmName: 'Labyrinth of Crops Farmstead',
      greenhouse: 'Vivid Vines Gardens',
      tomatoesDetected: 1875,
      stemsDetected: 491,
      creationDate: '01/08/2025',
    },
    {
      id: '8',
      farmName: 'Golden Fields Ranch',
      greenhouse: 'Sunlit Acres',
      tomatoesDetected: 6124,
      stemsDetected: 896,
      creationDate: '02/08/2025',
    },
    {
      id: '9',
      farmName: 'Rustic Roots Farm Sunlight',
      greenhouse: 'Meadow Bliss',
      tomatoesDetected: 582,
      stemsDetected: 179,
      creationDate: '02/08/2025',
    },
    {
      id: '10',
      farmName: 'Rustic Roots Farm Sunlight',
      greenhouse: 'Meadow Bliss',
      tomatoesDetected: 582,
      stemsDetected: 179,
      creationDate: '02/08/2025',
    },
    {
      id: '11',
      farmName: 'Rustic Roots Farm Sunlight',
      greenhouse: 'Meadow Bliss',
      tomatoesDetected: 582,
      stemsDetected: 179,
      creationDate: '02/08/2025',
    },
    {
      id: '12',
      farmName: 'Rustic Roots Farm Sunlight',
      greenhouse: 'Meadow Bliss',
      tomatoesDetected: 582,
      stemsDetected: 179,
      creationDate: '02/08/2025',
    },
  ];
  

export default DATA;